Avoiding conflict with the link helper
Without this change, it looks like the 'link' helper tries to deal with the `{{ link }}` element instead of the value coming from the context.  See the stack trace below for more detail.

        Assembling index.html  ERROR
        Warning: Cannot read property 'hash' of undefined Use --force to continue.
        TypeError: Cannot read property 'hash' of undefined
            at Object.Utils.isUndefined (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars-helpers/lib/utils/utils.js:87:97)
            at Object.module.exports.register.Handlebars.registerHelper.context (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars-helpers/lib/helpers/helpers-html.js:69:17)
            at Object.eval (eval at <anonymous> (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:564:23))
            at Handlebars.VM.template (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:30:33)
            at exports.attach.Handlebars.compile (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1274:21)
            at Object.Handlebars.VM.invokePartial (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:76:14)
            at Object.eval (eval at <anonymous> (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:564:23))
            at Handlebars.VM.template (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:30:33)
            at exports.attach.Handlebars.compile (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1274:21)
            at Object.Handlebars.VM.invokePartial (/Users/tschaub/projects/assemble-docs/node_modules/assemble/node_modules/assemble-handlebars/node_modules/handlebars/lib/handlebars/runtime.js:76:14)